"""
Django settings for sigo project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from mongoengine import connect
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o_+*-hwd5wrnu!%euxm4muoe^buvh0$t)&0xe*5un2+rf_ag7i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Cambiar a False en producción o en caso de pruebas de despliegue

ALLOWED_HOSTS = ['*'] # '127.0.0.1', 'localhost'-> para pruebas locales

CSRF_TRUSTED_ORIGINS = [
    "https://5474125d4e54.ngrok-free.app", # Dominnios temporales para pruebas de despliegue Ngrok u otros
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'system',
    'captcha',
]

# Configuración de middleware's
# https://docs.djangoproject.com/en/5.2/ref/settings/#middleware  
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Configuración de las URLs del proyecto
# https://docs.djangoproject.com/en/5.2/ref/settings/#root-urlconf
ROOT_URLCONF = 'sigo.urls'

# Configuración de las plantillas del proyecto
# https://docs.djangoproject.com/en/5.2/ref/settings/#templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sigo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Usa SQLite como base ficticia
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Conexión a MongoDB usando MongoEngine
MONGODB_SETTINGS = {
    'db': 'SystemSIGO',
    'host': 'mongodb+srv://edgaraimar0263:aMHr8Vi8G33MegHF@cluster0.qqwqgrn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
}


# Configuracipón del correo electrónico para notificaciones
# https://docs.djangoproject.com/en/5.2/topics/email/
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'al066230@uacam.mx'         # Cambiar por el correo del remitente
EMAIL_HOST_PASSWORD = 'pvkleqxdbicyqjre'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Configuración del captcha
RECAPTCHA_SITE_KEY = '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'
RECAPTCHA_SECRET_KEY = '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Configuración internacional de zona horaria e idioma
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Configuración del almacenamiento de archivos estáticos y multimedia

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

MEDIA_URL = '/images/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'static/images')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
